// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJjbKM1DTyma-hOoigNhWYaYT86jjpyCs',
    appId: '1:406646043845:web:d11862af57f694e62b6cac',
    messagingSenderId: '406646043845',
    projectId: 'mob3-uas-klp-9',
    authDomain: 'mob3-uas-klp-9.firebaseapp.com',
    storageBucket: 'mob3-uas-klp-9.firebasestorage.app',
    measurementId: 'G-4BTZSNFCW9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPohD1FMs3LdKfNb5Y6amC0nXRCzsWmBI',
    appId: '1:406646043845:android:b6cd97263f0982572b6cac',
    messagingSenderId: '406646043845',
    projectId: 'mob3-uas-klp-9',
    storageBucket: 'mob3-uas-klp-9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjE-MsB4ZyFiFevf4db6kuna_k8TRt9Qk',
    appId: '1:406646043845:ios:a204e1b844f8f8d62b6cac',
    messagingSenderId: '406646043845',
    projectId: 'mob3-uas-klp-9',
    storageBucket: 'mob3-uas-klp-9.firebasestorage.app',
    iosBundleId: 'com.example.mob3UasKlp09',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjE-MsB4ZyFiFevf4db6kuna_k8TRt9Qk',
    appId: '1:406646043845:ios:a204e1b844f8f8d62b6cac',
    messagingSenderId: '406646043845',
    projectId: 'mob3-uas-klp-9',
    storageBucket: 'mob3-uas-klp-9.firebasestorage.app',
    iosBundleId: 'com.example.mob3UasKlp09',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJjbKM1DTyma-hOoigNhWYaYT86jjpyCs',
    appId: '1:406646043845:web:01ab19190753365e2b6cac',
    messagingSenderId: '406646043845',
    projectId: 'mob3-uas-klp-9',
    authDomain: 'mob3-uas-klp-9.firebaseapp.com',
    storageBucket: 'mob3-uas-klp-9.firebasestorage.app',
    measurementId: 'G-BC6X2C8PFH',
  );
}
